include(
        "RoaringBitmap",
        "RoaringBitmapX",
        "bsi",
        "fuzz-tests",
        "jmh",
        "real-roaring-dataset",
        "examples",
        "simplebenchmark"
        )
